services:
  - type: web
    name: cece-rag-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: DEEPINFRA_API_TOKEN
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENV
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
    plan: free 